example/urls.py
from django.contrib import admin
from django.urls import path, include

from example import views
from example.views import (
    ExampleListView,
    ExampleCreateView,
    ExampleUpdateView,
    ExampleDeleteView,
    ExampleCompleteView,
)

urlpatterns = [
    path("list", ExampleListView.as_view(), name="example_list"),
    path("get-all", views.listAll, name="example_list_all"),
    path("create", ExampleCreateView.as_view(), name="example_create"),
    path("update/<int:pk>", ExampleUpdateView.as_view(), name="example_update"),
    path("delete/<int:pk>", ExampleDeleteView.as_view(), name="example_delete"),
    path("complete/<int:pk>", ExampleCompleteView.as_view(), name="example_complete"),
]

service_orders/urls.py
from django.urls import path

from example import views
from service_orders.views import (
    ServiceOrdersListView,
    ServiceOrdersCreateView,
    ServiceOrdersUpdateView,
    ServiceOrdersDeleteView,
    ServiceOrdersReadView,
    ServiceOrdersFinishView
)

urlpatterns = [
    path("list", ServiceOrdersListView.as_view(), name="service_orders_list"),
    path("create", ServiceOrdersCreateView.as_view(), name="service_orders_create"),
    path("update/<int:pk>", ServiceOrdersUpdateView.as_view(), name="service_orders_update"),
    path("delete/<int:pk>", ServiceOrdersDeleteView.as_view(), name="service_orders_delete"),
    path("read/<int:pk>", ServiceOrdersReadView.as_view(), name="service_orders_read"),
    path("finish/<int:pk>", ServiceOrdersFinishView.as_view(), name="service_orders_finish"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin", admin.site.urls),
    path('example', include('example.urls')),
    path('docs', include('documents.urls')),
    path('boards', include('boards.urls')),
    path('reservations', include('reservations.urls')),
    path('convocations', include('convocations.urls')),
    path('service-orders', include('service_orders.urls')),
    path('', include('users.urls')),
    path('users', include('django.contrib.auth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

convocations/models.py
from django.db import models

class Convocations(models.Model):
    title = models.CharField(verbose_name="Título", max_length=100)
    description = models.CharField(verbose_name="Descrição", max_length=100)
    doc_url = models.FileField(verbose_name="Documento", null=False, blank=False, upload_to="convocations/")
    created_at = models.DateTimeField(auto_now_add=True, max_length=100, null=False, blank=False)
    updated_at = models.DateTimeField(auto_now=True, max_length=100)
    deleted_at = models.DateTimeField(null=True)

example/models.py
from datetime import date
from django.db import models


class Example(models.Model):
    title = models.CharField(
        verbose_name="Título", max_length=100, null=False, blank=False
    )
    created_at = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    deadline = models.DateField(verbose_name="Data de entrega", null=False, blank=False)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    finished_at = models.DateField(null=True)

    class Meta:
        ordering = ["deadline"]

    def mark_has_complete(self):
        if not self.finished_at:
            self.finished_at = date.today()
            self.save()

service_orders/models.py
from django.conf import settings
from django.db import models
from datetime import date, datetime

class ServiceOrders(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    image_url = models.ImageField(null=True, blank=True, upload_to="service_orders/") 
    title = models.CharField(verbose_name="Título", max_length=100) 
    description = models.CharField(verbose_name="Descrição", max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, max_length=100, null=False, blank=False)
    read_at = models.DateTimeField(null=True)
    finished_at = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(auto_now=True, max_length=100)
    deleted_at = models.DateTimeField(null=True)
    
    def mark_has_read(self):
        if not self.read_at:
            self.read_at = datetime.now()
            self.save()
    
    def mark_has_finished(self):
        if not self.finished_at:
            self.finished_at = datetime.now()
            self.save()

example/views.py
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from example.serializer import ItemSerializer

from .models import Example


class ExampleListView(LoginRequiredMixin, ListView):
    model = Example

def listAll(request):
    model = Example
    serializer = ItemSerializer(model.objects.all(), many =True)
    return JsonResponse(serializer.data, safe =False)

class ExampleCreateView(LoginRequiredMixin, CreateView):
    model = Example
    fields = ["title", "deadline", "image"]
    success_url = reverse_lazy("example_list")

class ExampleUpdateView(LoginRequiredMixin, UpdateView):
    model = Example
    fields = ["title", "deadline", "image"]
    success_url = reverse_lazy("example_list")

    """ def form_valid(self, form):
        form.instance.title = self.request.user.id
        return super(ExampleUpdateView, self).form_valid(form) """

class ExampleDeleteView(LoginRequiredMixin, DeleteView):
    model = Example
    success_url = reverse_lazy("example_list")

class ExampleCompleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        example = get_object_or_404(Example, pk=pk)
        example.mark_has_complete()
        return redirect("example_list")

service_orders/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import ServiceOrders


class ServiceOrdersListView(LoginRequiredMixin, ListView):
    model = ServiceOrders

class ServiceOrdersCreateView(LoginRequiredMixin, CreateView):
    model = ServiceOrders
    fields = ["title", "description", "image_url"]
    success_url = reverse_lazy("service_orders_list")
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ServiceOrdersCreateView, self).form_valid(form)

class ServiceOrdersUpdateView(LoginRequiredMixin, UpdateView):
    model = ServiceOrders
    fields = ["title", "description", "image_url"]
    success_url = reverse_lazy("service_orders_list")
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ServiceOrdersUpdateView, self).form_valid(form)

class ServiceOrdersDeleteView(LoginRequiredMixin, DeleteView):
    model = ServiceOrders
    success_url = reverse_lazy("service_orders_list")

class ServiceOrdersReadView(LoginRequiredMixin, View):
    def get(self, request, pk):
        serviceOrder = get_object_or_404(ServiceOrders, pk=pk)
        serviceOrder.mark_has_read()
        return redirect("service_orders_list")
    
class ServiceOrdersFinishView(LoginRequiredMixin, View):
    def get(self, request, pk):
        serviceOrder = get_object_or_404(ServiceOrders, pk=pk)
        serviceOrder.mark_has_finished()
        return redirect("service_orders_list")

example/templates/service_orders/serviceorders_confirm_delete.html
{% extends 'base.html' %}

{% block page_title %}
    Excluír Ordem de Serviço
{% endblock page_title %}

{% block content %}
    <h1>Excluír Ordem de Serviço?</h1>

    <p>Tem certeza que deseja excluír a ordem de serviço <strong>{{ serviceorders.title }}</strong>?</p>

    <form method="POST">
        {% csrf_token %}

        <button type="submit" class="btn btn-danger">Excluír</button>
        <a href="{% url 'convocations_list' %}" class="btn btn-primary">Cancelar</a>
    </form>
{% endblock content %}

example/templates/service_orders/serviceorders_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}
  {% if serviceorders.pk %}
    Editar Ordem de Serviço
  {% else %}
    Nova Ordem de Serviço
  {% endif %}
{% endblock page_title %}

{% block content %}
  {% if serviceorders.pk %}
    <h1>Editar ordem de serviço</h1>
  {% else %}
    <h1>Nova ordem de serviço</h1>
  {% endif %}

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock content %}

    

example/templates/service_orders/serviceorders_list.html
{% extends 'base.html' %}

{% block page_title %}
    Lista de Ordens de Serviço
{% endblock page_title %}

{% block content %}
    <h1>Lista de Ordens de Serviço</h1>

    {% if serviceorders_list %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Descrição</th>
                <th scope="col">Criado em</th>
                <th scope="col">Visto em</th>
                <th scope="col">Finalizado em</th>
                <th scope="col">Imagem</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
                {% for serviceorder in serviceorders_list %}
                    <tr>
                        <th scope="row">{{ serviceorder.pk }}</th>
                        <td>{{ serviceorder.title }}</td>
                        <td>{{ serviceorder.description }}</td>
                        <td>{{ serviceorder.created_at }}</td>
                        <td>{{ serviceorder.read_at }}</td>
                        <td>{{ serviceorder.finished_at }}</td>
                        <td><img src="{{ serviceorder.image_url.url }}" width=100></td>
                        <td>
                            <a
                                href="{% url 'service_orders_update' pk=serviceorder.pk %}" 
                                class="btn btn-secondary btn-sm {% if serviceorder.finished_at %}disabled{% endif %}"
                            >
                                Editar
                            </a>
                            {% if user.is_staff %}
                                <a href="{% url 'service_orders_read' pk=serviceorder.pk %}" class="btn btn-secondary btn-sm {% if serviceorder.read_at %}disabled{% endif %}">Reconhecer</a>
                                <a href="{% url 'service_orders_finish' pk=serviceorder.pk %}" class="btn btn-secondary btn-sm {% if serviceorder.finished_at %}disabled{% endif %}">Finalizar</a>
                            {% endif %}
                            <a href="{% url 'service_orders_delete' pk=serviceorder.pk %}" class="btn btn-danger btn-sm">Excluír</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Não há ordens de serviço lançadas pelo condomínio</p>
    {% endif %}
    
    <a href="{% url 'service_orders_create' %}" class="btn btn-primary">Nova Ordem de Serviço</a>

{% endblock content %}